version: "2.1"
services:
  nodejs:
    image: node:6.11.1
    working_dir: /apps/warehouse
    volumes:
      - .:/apps/warehouse
      - ./wait-for:/wait/wait-for
    command: tail -f /dev/null
  lb:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.warehouse.conf:/etc/nginx/conf.d/default.conf
      - ./wait-for:/wait/wait-for
      - /opt/logsdata:/var/log/nginx
    depends_on:
      - web
    ###
    # 1. Found the nginx image's default command here:
    # https://github.com/nginxinc/docker-nginx/blob/7e278fff2f12f852ef1be2aed17e9a2f822365ac/stable/stretch/Dockerfile#L43
    # CMD ["nginx", "-g", "daemon off;"]
    #
    # 2. the nginx image doesn't have `nc` (netcat) or `curl` so we can't use the `wait-for` script
    ###
    #command: ["/wait/wait-for", "web:3000", "--", "nginx", "-g", "daemon off;"]
  web:
    build: .
    ports:
      - "3000"
    environment:
      NODE_ENV: staging
      MONGOLAB_URI: mongodb://db:27017/warehouse-local
    env_file: .env
    command: node server/server.js
    volumes:
      - ./client/app/images:/apps/warehouse/client/app/images
      - ./client/app/scripts:/apps/warehouse/client/app/scripts
      - ./client/app/styles:/apps/warehouse/client/app/styles
      - ./client/app/views:/apps/warehouse/client/app/views
      - ./client/app/index.html:/apps/warehouse/client/app/index.html
      - ./common:/apps/warehouse/common
      - ./server:/apps/warehouse/server
      - ./package.json:/apps/warehouse/package.json
      - ./npm-shrinkwrap.json:/apps/warehouse/npm-shrinkwrap.json
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web:3000/api/StoreModels"]
      interval: 15s
      timeout: 10s
      retries: 3
  worker-web:
    build: .
    ports:
      - "3000"
    environment:
      NODE_ENV: staging
      MONGOLAB_URI: mongodb://db:27017/warehouse-local
    env_file: .env
    entrypoint: /docker-entrypoint.sh
    command: ["/wait/wait-for", "web:3000", "--", "node","server/server.js"]
    volumes:
      - ./common:/apps/warehouse/common
      - ./server:/apps/warehouse/server
      - ./package.json:/apps/warehouse/package.json
      - ./npm-shrinkwrap.json:/apps/warehouse/npm-shrinkwrap.json
      - ./wait-for:/wait/wait-for
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    depends_on:
      - web
      - db
  db:
    image: mongo:3.2
    ports:
      - "27020:27017"
